version: 1.0.{build}
image: Visual Studio 2019

shallow_clone: true
clone_depth: 1
install:
  - set "PATH=C:\DXSDK;C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%"
  - set MSYSTEM=MINGW32
  - set PreferredToolArchitecture=x86
  - choco install nasm
  - set PATH="C:\Program Files\NASM";%PATH%
build_script:
  - 7z a fbn-code.7z %APPVEYOR_BUILD_FOLDER%\*      
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && mingw32-make mingw510 -j5 RELEASEBUILD=1 SKIPDEPEND=1 USE_UCRT=1"
  - 7z a fbn-win32-gcc.7z %APPVEYOR_BUILD_FOLDER%\*.exe %APPVEYOR_BUILD_FOLDER%\fba.chm  %APPVEYOR_BUILD_FOLDER%\*.zip %APPVEYOR_BUILD_FOLDER%\src\license.txt %APPVEYOR_BUILD_FOLDER%\whatsnew.html      
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && rm -rf obj && mingw32-make mingw510 -j5 SKIPDEPEND=1 USE_UCRT=1"
  - 7z a fbn-win32-debug-gcc.7z %APPVEYOR_BUILD_FOLDER%\fbneod.exe %APPVEYOR_BUILD_FOLDER%\fba.chm  %APPVEYOR_BUILD_FOLDER%\*.zip %APPVEYOR_BUILD_FOLDER%\src\license.txt %APPVEYOR_BUILD_FOLDER%\whatsnew.html        

artifacts:
  - path: fbn-code.7z
    name: source
  - path: fbn-win32-gcc.7z
    name: win32-bin-gcc  
  - path: fbn-win32-debug-gcc.7z
    name: win32-bin-debug-gcc	
# Test scripts
test: off

deploy:
- provider: GitHub
  tag: appveyor-build
  description: github-commit-%APPVEYOR_REPO_COMMIT%
  force_update: true
  on:
    branch: master                 # release from master branch only 
  auth_token:
    secure: cC6FjF22axzOF1Y1+B2DfieS+B3KAHeUTefa7k/iq7MJjqaj/OjQ01EWN+Ga5r6v
  repository: finalburnneo/FBNeo-WIP-Storage-Facility
  artifact: source, win32-bin-gcc, win32-bin-debug-gcc
  
